#ifndef __PCBOVEN_USB_H__
#define __PCBOVEN_USB_H__

#include <linux/ioctl.h>

#define PCBOVEN_USB_ID_VENDOR      0x03EB
#define PCBOVEN_USB_ID_PRODUCT     0x3140

#define PCBOVEN_IOCTL_MAGIC        0xA1
#define PCBOVEN_MISC_MINOR         0x54

#define PCBOVEN_IS_CONNECTED       _IOR(PCBOVEN_IOCTL_MAGIC, 'C', int)
#define PCBOVEN_SET_TEMPERATURE    _IOW(PCBOVEN_IOCTL_MAGIC, 'T', int)
#define PCBOVEN_ENABLE_FILAMENTS   _IO(PCBOVEN_IOCTL_MAGIC, 'E')
#define PCBOVEN_DISABLE_FILAMENTS  _IO(PCBOVEN_IOCTL_MAGIC, 'D')

#endif

